version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRS_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  spring_boot_app:
    image: alexkp/hr_administration
    container_name: application
    restart: always
    ports:
      - 8080:8080
    links:
      - db